modLoader="javafml"
license="${mod_license}"
loaderVersion="${neoforge_loader_version_range}"
issueTrackerURL="${mod_issues}"
displayURL="${mod_page}"
logoFile="${mod_id}_logo.png"

[[mixins]]
config="${mod_id}-common.mixins.json"

[[mixins]]
config="${mod_id}-neoforge.mixins.json"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description="${mod_description}"

[[dependencies.${mod_id}]]
modId="neoforge"
required=true
versionRange="${neoforge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"